name: Retrain Model

on:
  schedule:
    - cron: '55 15 * * *'  # ✅ Runs at 11:55 PM UTC every day
  workflow_dispatch:       # Allows manual triggering

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     

      - name: Run retraining script
        run: python train_model.py
